---
# file: roles/py_artifact/tasks/main.yml

- name: Build the setting.py file
  template:
    src: settings.py.j2
    dest: "{{ app_src_dir }}/backend/backend/app/settings.py"

- name: Build the setup.py file
  template:
    src: setup.py.j2
    dest: "{{ app_src_dir }}/backend/setup.py"

- name: Build the artifact
  command:
    python setup.py sdist \
    chdir={{ app_src_dir }}/backend
