# Set the base image to Nginx
FROM nginx

# File Author / Maintainer
MAINTAINER Emiliano Molina <emiliano.molina@intel.com>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
