---
# file: roles/reverse_proxy_image/task/main.yml

- name: Build the reverse proxy image
  docker_image:
    docker_url: unix://var/run/docker.sock
    name: "{{ app_maintainer_username }}/nginx"
    path: roles/reverse_proxy_image/files
    state: present
    tag: latest
