---
# file: roles/multi_container/tasks/main.yml

- name: Run the log data container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    docker_url: unix://var/run/docker.sock
    image: "{{ app_maintainer_username }}/log_data:latest"
    name: log_data
    restart_policy: on-failure
    state: reloaded

- name: Run the cache container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    docker_url: unix://var/run/docker.sock
    image: "{{ app_maintainer_username }}/redis:latest"
    name: local_cache
    restart_policy: on-failure
    state: reloaded

- name: Run the web server containers
  docker:
    docker_api_version: "{{ docker_api_version }}"
    docker_url: unix://var/run/docker.sock
    image: "{{ app_maintainer_username }}/{{ app_name }}:{{ app_version }}"
    links: 
      - local_cache
    name: "{{ app_name }}_{{ item }}"
    restart_policy: on-failure
    state: reloaded
    volumes_from: 
      - log_data
  with_sequence: count={{ ansible_processor_vcpus }}

- name: Run the reverse proxy container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    docker_url: unix://var/run/docker.sock
    image: "{{ app_maintainer_username }}/nginx:latest"
    links:
      - echo_service_1
    name: reverse_proxy
    ports: 
      - 80:80
    restart_policy: on-failure
    state: reloaded
