---
# file: roles/app_img/tasks/main.yml

- name: Create files directory
  file:
    path: roles/app_img/files
    state: directory

- name: Build the Dockerfile file
  template:
    src: Dockerfile.j2
    dest: "{{ app_src_dir }}/backend/Dockerfile"

- name: Build the image
  docker_image:
    docker_url: unix://var/run/docker.sock
    name: "{{ app_maintainer_username }}/{{ app_name  }}"
    path: "{{ app_src_dir }}/backend"
    state: present
    tag: "{{ app_version }}"
