---
# file: roles/container/tasks/main.yml

- name: Run the web server container
  docker:
    env: "{{ conf }}"
    docker_api_version: "{{ docker_api_version }}"
    docker_url: unix://var/run/docker.sock
    image: "{{ app_maintainer_username }}/{{ app_name }}:{{ app_version }}"
    name: "{{ app_name }}"
    ports:
      - 8080:8080
    restart_policy: on-failure
    state: reloaded
